name: Anigalaxy
on:
  workflow_dispatch:
  schedule:
    - cron: '0/20 * * * *'
jobs:
  build:
    runs-on: windows-latest           
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Run
      run: dotnet run -c Debug -- --token=${{ secrets.TELEGRAM_BOT_TOKEN }} -c -1001251996661 --tags=genshin_impact%ass%pussy%open_shirt%pantsu%girls_und_panzer%animal_ears%loli%trap%wet%naked%bottomless%seifuku%undressing%uniform%bunny_ears%bunny_girl%nekomimi%neko%hatsune_miku%re_zero_kara_hajimeru_isekai_seikatsu%maid%honkai:_star_rail%wallpaper%bocchi_the_rock!%yuri%darling_in_the_franxx%neon_genesis_evangelion%sono_bisque_doll_wa_koi_wo_suru%kono_subarashii_sekai_ni_shukufuku_wo%ijiranaide_nagatoro-san%code_geass%1girl%breasts%school_uniform%solo