name: Caeoq
on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest           
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Run
      run: dotnet run -c Debug -- --grabtags --mintagscount 10 --token=${{ secrets.TELEGRAM_BOT_TOKEN }} -c -1001919422070 --bannedtags=furry%furry_female%1boy --usepixiv --pixivrefresh=${{ secrets.PIXIV_REFRESH_TOKEN }} --useyandere --usegelbooru --grabbannedtags --usedanboorudonmai --usesankakucomplex --uselolibooru --useanimepictures