name: Hentaibox
on:
  workflow_dispatch:
  schedule:
    - cron: '0/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest           
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run
      run: dotnet run -c Debug -- --token=${{ secrets.TELEGRAM_BOT_TOKEN }} -c -1001789721125 --bannedtags=furry%furry_female%1boy%multiple_boys%aged_down --useanimepictures --useyandere --usegelbooru --grabbannedtags --usedanboorudonmai --usesankakucomplex --uselolibooru --userule34