name: nyanart
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest           
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Run
      run: dotnet run -c Debug -- --token=${{ secrets.TELEGRAM_BOT_TOKEN }} -c -1001761383404 --rating Safe --bannedtags=furry&furry_female
