name: omo
on:
  workflow_dispatch:
  schedule:
    - cron: '0/20 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest           
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Run
      run: dotnet run -c Debug -- --token=${{ secrets.TELEGRAM_BOT_TOKEN }} --usepixiv --pixivrefresh=${{ secrets.PIXIV_REFRESH_TOKEN }} -c -1001836193798 --rating Explicit --tags=女の子%ロリ%美少女%日常%AIイラスト%AI生成%原神%ホロライブ%VTuber%崩坏星穹铁道%新世紀エヴァンゲリオン%エヴァンゲリオン%DARLINGintheFRANXX%リゼロ%コードギアス%初音ミク%ヘヴィーオブジェクト%キルラキル%猫
